



# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Remove the conditional block to avoid defaulting to local socket
  # <% if ENV["DB_HOST"] %>
  # host: <%= ENV["DB_HOST"] %>
  # username: postgres
  # password: postgres
  # <% end %>

development:
  <<: *default
  database: melow_development

test:
  <<: *default
  database: melow_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: melow_production
  username: melow
  password: <%= ENV["MELOW_DATABASE_PASSWORD"] %>

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: melow_staging
  username: melow
  password: <%= ENV["MELOW_DATABASE_PASSWORD"] %>
